# Spring Boot Configuration
spring:
  application:
    name: claude-automator

# Logging Configuration
logging:
  level:
    root: INFO
    com.claude.automator: INFO
    io.github.jspinak.brobot: INFO
    io.github.jspinak.brobot.logging.unified: WARN  # Reduce unified logging verbosity
    io.github.jspinak.brobot.statemanagement: WARN
    io.github.jspinak.brobot.lifecycle: WARN
    io.github.jspinak.brobot.action.basic.find: WARN
    io.github.jspinak.brobot.startup: INFO  # Keep startup at INFO
    io.github.jspinak.brobot.aspects.display: DEBUG  # Debug visual feedback
    io.github.jspinak.brobot.tools.logging.visual: DEBUG  # Debug highlight manager
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"  # Cleaner timestamp format

# Brobot Configuration (v1.1.0+)
# Only override values that differ from defaults in brobot-defaults.properties
brobot:
  core:
    image-path: images
    mock: false
  screenshot:
    save-history: true
  force:
    headless: false
  allow:
    screen:
      capture: true
  startup:
    # Enable automatic startup verification
    auto-verify: true
    verify-states: "Working,Prompt"  # States to verify
    image-path: images
    fallback-paths:
      - "/home/jspinak/brobot-parent-directory/claude-automator/images"
    clear-states-before-verify: true
    ui-stabilization-delay: 2.0
    throw-on-failure: false
    run-diagnostics-on-failure: true
    # Legacy settings
    verify-initial-states: false
    initial-states: ""
    startup-delay: 2
  sikuli:
    highlight: true
  # Highlighting configuration
  highlight:
    # Method: SIKULI (default), JAVAFX, TAURI, or AUTO
    # AUTO will try in order: Tauri > JavaFX > SikuliX
    method: AUTO
    fallback:
      enabled: true
    default-duration: 2.0
    default-color: "#00FF00"  # Green for Claude automation
    default-style: BORDER
    verbose: false
    # Tauri service settings
    tauri:
      timeout: 5000
      port: 7890
    # JavaFX settings
    javafx:
      animation-enabled: true
    # SikuliX settings
    sikuli:
      scale-adjustment: true
      dpi-aware: true
  monitor:
    # Use primary monitor by default (-1 = primary)
    default-screen-index: -1
    multi-monitor-enabled: true
    log-monitor-info: true
  # Console action reporting - shows detailed action results
  console:
    actions:
      enabled: true
      level: NORMAL  # QUIET, NORMAL, or VERBOSE
      # VERBOSE shows: match coordinates, similarity scores, timing details
      # NORMAL shows: success/failure and target name only
      # QUIET shows: no action output
      show-match-details: false
      show-timing: false
      use-symbols: true  # Use ▶, ✓, ✗ symbols
  # Combined logging configuration
  logging:
    # Action logging verbosity
    verbosity: NORMAL  # NORMAL or VERBOSE
    # VERBOSE includes: search regions, performance metrics, stack traces
    # NORMAL includes: basic operation results only
    verbose:
      show-search-regions: false
      show-match-scores: false
      show-performance-breakdown: false
      show-stack-traces: false
    normal:
      show-timing: false
      show-match-coordinates: false
      show-match-count: false
    # Unified logging configuration
    console:
      level: NORMAL        # Reduce duplicate logging
      colors: true          # Enable ANSI colors
      format: compact      # Use compact format
      duplicate-to-slf4j: false  # Prevent duplicate [INFO] lines
    structured:
      enabled: true         # Enable structured logging
      format: json          # Log in JSON format
      sink: file           # Write to file
      file:
        path: logs/claude-automator-structured.json
        rotation: daily
        max-size: 100MB
    performance:
      enabled: true         # Track performance metrics
      metrics-export: none  # No external metrics export for now
    context:
      include-thread-name: true
      include-timestamp: true
      include-hostname: false

# Claude Automator specific configuration
claude:
  automator:
    monitoring:
      check-interval: 2     # seconds between icon checks
      initial-delay: 5      # seconds before first check
      icon-timeout: 5       # seconds to wait for icon